---
title: "Ruoxi Li"
output: 
  html_document:
    toc: true
    toc_float: true
---

## About me

I am Ruoxi Li, a graduate student specializing in Biostatistics at Columbia University's Irving Medical Center. Holding a Bachelor's degree in Preventive Medicine, my academic foundation is deeply rooted in the prevention and mitigation of health risks. My passion lies in harnessing the power of biostatistical methods to address medical challenges, with a particular focus on clinical trials and the development of new drugs.

## Skills

In terms of technical skills, I primarily utilize R for data analysis. Additionally, I have practical experience with SAS and SPSS, allowing me to proficiently handle and analyze data using these tools.

## Facts about me

1. My previous internships were in hospitals, disease control centers, and public health service centers in various places.
2. I am currently seeking internship opportunities in the industry.
3. I am a TV series enthusiast.
4. I have a cow cat in China.

Learn more about my academic and professional experience: [resume](resume.html)


